### ISSUE TITLE
Primary source is down

### ISSUE THREAD

**Issue by YuruiHong** [retorquere/zotero-deb#105]
The primary source is no longer usable and I have to switch to https://mirror.mwt.me/zotero/deb

**Comment by retorquere** [comment]
I have tested from my own system, and from the github infrastructure, and both can update apt and (re)install from the primary.

**Comment by retorquere** [comment]
What error(s) are you seeing, precisely?

**Comment by retorquere** [comment]
I've added a browsable index at https://zotero.retorque.re/file/apt-package-archive, but

* since I don't know what errors you are seeing
* I cannot replicate any problems installing the packages from any systems I have access to
* I can download all files from https://zotero.retorque.re/file/apt-package-archive

there's really nothing for me to fix as far as I can tell. If you don't offer more information I am going to have to close this issue.

**Comment by YuruiHong** [comment]
Sorry for the delay. For several days `apt update` failed and when I tried to visit https://zotero.retorque.re/file/apt-package-archive/index.html I was redirected to another site. Cannot reproduce now so no more details.

**Comment by retorquere** [comment]
The redirect didn't mean that the repo was down, repos aren't regular websites (necessarily). I've added an index page, but that is there alongside the repo, not because of it.

**Comment by retorquere** [comment]
I get notified within two hours should the repo go down (and then every two hours until I fix it).

**Comment by retorquere** [comment]
> I was redirected to another site

To *another site*? That is sus. The repo doesn't do that.
