### ISSUE TITLE
Alternative packages with extensions ?

### ISSUE THREAD

**Issue by ngirard** [retorquere/zotero-deb#14]
How about offering alternative packages that would be built with the extensions <del>everybody</del> many people are using ? Namely:

- Better BibTeX for Zotero ;
- Zotero LibreOffice integration ;
- Zotero report customizer ;
- ZotFile ;
- Zutilo

Setting-up a working Zotero environment is painful enough -- I'm sure many people would be glad to find these packages.

In the case when someone would need all of the abovementioned extensions *except* BBT, for instance, well then, it would still be much easier use such a package and disable BBT, rather than installing the 4 other extensions by hand.

Any thoughts ?

**Comment by retorquere** [comment]
This should really be handled (if at all) as separate .deb packages with a dependency on the presence of "zotero or jurism" (this is possible with debs, although I have no idea how to bring it about), but it's tricky as I don't really know what Firefox expects to be done for preinstalled extensions. I certainly wouldn't want to bundle Zotero+anything because the Zotero devs would be right to reject support requests for such bundles. Even for BBT they often say "remove BBT while we diagnose this problem", and I don't blame them.

I'm inclined to think that the Zotero built-in package installer is sufficiently user-friendly to handle installations. The debs came about because I think the installation process of Zotero has more stuff you need to put into place before it works really well (desktop file, file associations, now the symlink to bin, whatnot) that don't apply to the plugins.
