### ISSUE TITLE
Failed to create gpg file

### ISSUE THREAD

**Issue by Bha91** [retorquere/zotero-deb#73]
I've tried installing on ubuntu 20.04 using:
`curl -sL https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash
`
but got:
`Warning: Failed to create the file 
Warning: /usr/share/keyrings/zotero-archive-keyring.gpg: Read-only file system
 69  1150   69   802    0     0    550      0  0:00:02  0:00:01  0:00:01   550
curl: (23) Failure writing output to destination
chmod: cannot access '/usr/share/keyrings/zotero-archive-keyring.gpg': No such file or directory
deb [signed-by=/usr/share/keyrings/zotero-archive-keyring.gpg by-hash=force] https://zotero.retorque.re/file/apt-package-archive .`

**Comment by retorquere** [comment]
> Read-only file system

That is your problem right there. I'm not sure how you started, but if the script (or you) can't write to that location, nothing will work .

**Comment by retorquere** [comment]
Were you able to get that location writable?

**Comment by tsamakos** [comment]
I have the exact same issue. I tried with chmod 777, but it did not work.

**Comment by retorquere** [comment]
You do not want to have that location world-writable.

As far as I can tell, for the original poster, the filesystem was mounted read-only, a boot-time option, possibly in `fstab`. Look for a gui to change that, if you don't know what you are doing, the wrong edit would leave your system unbootable. It is not normal to have that place mounted read-only, something must have forced your system to mount the drive in some sort of "safe mode". 

A read-only filesystem means no write of any kind van succeed there, the chmod might very well have done nothing because of it. Reboot your system and look at the permissions of the directory of the file/directory you applied the `chmod` to.

**Comment by mbelda** [comment]
Same here. You sure is our issue?

**Comment by retorquere** [comment]
[This](https://askubuntu.com/questions/197459/how-to-fix-sudo-unable-to-open-read-only-file-system) lists some possible reasons why the filesystem might have ended up read-only, but I'd advice posting your own question there rather than randomly trying commands to mess with your filesystem, unless you understand what these commands (can) do. If you have consistency errors, it wouldn't be hard to make matters worse.
