### ISSUE TITLE
do you consider an entry in distribution's repositories?

### ISSUE THREAD

**Issue by nbehrnd** [retorquere/zotero-deb#77]
If the project's aim is to facilitate the installation of zotero in .deb based Linuxes, is it because of license incompatibility with GNU Affero GPL 3 of zotero ([source](https://github.com/zotero/zotero/blob/master/COPYING)) the repository of zotero-deb does not use a license entry in the descriptive column?  Below a comparison with [openbabel](https://github.com/openbabel/openbabel/), an other project hosted on GitHub:

![comparison](https://user-images.githubusercontent.com/19709084/164625390-bfff3738-020b-49c9-9bdc-e3277e1a4bf6.png)

Second to this, because this project is mentioned e.g., in the French Ubuntu community page [ubuntu-fr.org](https://doc.ubuntu-fr.org/zotero), is it because of license incompatibility that your project is not yet among the packages listed e.g., by Debian's [package tracker](https://tracker.debian.org/)? (Because I do not use Ubuntu, I do not know the functionality offered by [unity-scope-zotero](https://packages.ubuntu.com/search?keywords=zotero&searchon=names&suite=all&section=all) identified by Ubuntu's [package directories](https://packages.ubuntu.com/).)

**Comment by retorquere** [comment]
> If the project's aim is to facilitate the installation of zotero in .deb based Linuxes, is it because of license incompatibility with GNU Affero GPL 3 of zotero ([source](https://github.com/zotero/zotero/blob/master/COPYING)) the repository of zotero-deb does not use a license entry in the descriptive column? Below a comparison with [openbabel](https://github.com/openbabel/openbabel/), an other project hosted on GitHub:

I just didn't think about the license. I've added a MIT license to the repo. I don't think there's a license incompatibility, my scripts are not a derivative work of the Zotero sources, they pick up Zotero *binaries* and package them. My scripts are wholly separate from the Zotero sources.

> Second to this, because this project is mentioned e.g., in the French Ubuntu community page [ubuntu-fr.org](https://doc.ubuntu-fr.org/zotero), is it because of license incompatibility that your project is not yet among the packages listed e.g., by Debian's [package tracker](https://tracker.debian.org/)? (Because I do not use Ubuntu, I do not know the functionality offered by [unity-scope-zotero](https://packages.ubuntu.com/search?keywords=zotero&searchon=names&suite=all&section=all) identified by Ubuntu's [package directories](https://packages.ubuntu.com/).)

My scripts are not Zotero; I don't see my packaging scripts as interesting for distribution themselvees.

That aside, Zotero as it stands cannot be offered for inclusion in Debian because as part of the building the zotero source, Firefox binaries are downloaded and used as-is in Zotero, and that is not allowed in Debian packages.
