### ISSUE TITLE
What is the zotero-deb release cycle?

### ISSUE THREAD

**Issue by ReinPeacock** [retorquere/zotero-deb#93]
I've noticed zotero-deb is on 6.0.27 from 5 Sept 2023, while the most recent release of Zotero is 6.0.30 from 2 Nov 2023. No major changes between that one and the latest, and I don't use Word. Looks like 6.0.27 was the last release with any significant changes? Is zotero-deb only updated where the changelog has changes in bold for that release? It's fine either way. Thanks.

**Comment by ReinPeacock** [comment]
`curl -sL https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash` doesn't update it from 6.0.27.

**Comment by retorquere** [comment]
That's the one-time install of the pointer to the repository. To get updates (now and later) you still need to run `apt update` and `apt upgrade`.

**Comment by ReinPeacock** [comment]
Not working. I get as it's updating the package list `Get:6 https://zotero.retorque.re/file/apt-package-archive ./ InRelease [2,153 B]
`, but it says all packages are up to date.

**Comment by retorquere** [comment]
> Not working. I get as it's updating the package list `Get:6 https://zotero.retorque.re/file/apt-package-archive ./ InRelease [2,153 B] `, but it says all packages are up to date.

This must be the result of `apt update`, which only updates your registry. The actual software update happens by `apt upgrade`. The update process for Debian-based systems consists of:

1. A one-time install to tell `apt` about a new software repository, and then regularly
2. `apt update`, which tells `apt` to get the latest information from all your installed repos, which will give it information whether any upgrades exist, followed by
3. `apt upgrade`, which checks which software is out of date given the information `apt update` retrieved in step 2 and performs installs as necessary.

If you only do step 2, no upgrades happen, because that's not what `update` does. If you only do step 3, no upgrades happen because `apt` doesn't know any are available.

The GUI tools of your distro will guide you through step 2 and 3. It doesn't need to be done from the command line.

**Comment by retorquere** [comment]
What is the output of

```
apt-cache madison zotero
```

and

```
dpkg -l zotero
```

**Comment by ReinPeacock** [comment]
```
apt-cache madison zotero
    zotero |     6.0.30 | https://zotero.retorque.re/file/apt-package-archive ./ Packages
    zotero |     6.0.27 | https://zotero.retorque.re/file/apt-package-archive ./ Packages
    zotero |     6.0.26 | https://zotero.retorque.re/file/apt-package-archive ./ Packages
    zotero |     6.0.25 | https://zotero.retorque.re/file/apt-package-archive ./ Packages
    zotero |     6.0.24 | https://zotero.retorque.re/file/apt-package-archive ./
```

```
dpkg -l zotero
dpkg-query: no packages found matching zotero
```

**Comment by retorquere** [comment]
There's a final `Packages` missing in the `apt-cache madison zotero`, but that could just be a copy-paste problem. But the output from `dpkg -l zotero` means that however you installed zotero previously, it wasn't through the `apt` package manager, and ipso facto not from my repo.

If I'd have to guess you might have installed zotero using the tarball from https://www.zotero.org/download. What does `which zotero` say?

**Comment by ReinPeacock** [comment]
`which zotero` has no output. It's possible I installed via tarball and then forgot about it.

**Comment by retorquere** [comment]
As long as `/usr/bin/zotero`and `/usr/lib/zotero/` do not exist it should be safe to just install it using `apt install zotero`.

**Comment by ReinPeacock** [comment]
Ok, that worked. Thanks. Just need to figure out how to merge data in old Zotero into new one, and remove old Zotero.

**Comment by retorquere** [comment]
There should be nothing to merge -- if you kept to the default setup for the tarball, the packaged zotero will find and use your existing data

**Comment by retorquere** [comment]
If the snap held to the zotero recommendations, your data should be isolated in `~/Zotero` and should be untouched by uninstall/reinstall, but I don't know whether the snap does.
